language: cpp
branches:
  only:
    - master
    - develop
    - feature/vector
compiler:
  - clang++
os: osx
osx_image: xcode8

install:
  - mkdir build
  - cd build
  - cmake -Dtest=ON .. && make
script: ./../bin/tests/avx-optimization-test
